### PR TITLE
Initial prune of Node-as-a-Service Providers

### PR DESCRIPTION
**Pull request by derekpierre**
Remove companies in the list don't currently support NuCypher. To make the review simple, just look at the changes made to README.md - ended up with 7 companies remaining.

Two outstanding comments:
1. "Hashquark" seems weird: https://www.hashquark.io/#/staking/nu - they just list a worker address on their site, unsure of viability, and hopefully as a worker is used a new one is provided on the site. I left it in for now - does anyone have insight here?
2. "itokenpool" claimed to support but only pointed users to a wechat group without more information on their site. I removed them as an entry, but if someone has additional insight here, I can add them back.

### CODE REVIEW

**Comment by mswilkison** [comment]
I don't have any insight in either Hashquark or itoken. Re: hashquark is that worker bonded? Seems like most likely they're just running their own node.

**Comment by derekpierre** [comment]
> Re: hashquark is that worker bonded?

It is bonded, but the associated staker's stake is now expired:
```
Checksum address                            Staker information
=================================================================================================
0xd1089adDb272221e2df019CA91395c488E83F656  Nickname:  LightCyan Charlie Cornsilk Papa [CP]
                                            Owned:     0 NU
                                            Staked in current period: 0 NU
                                            Staked in next period: 0 NU
                                            Unlocked: 0 NU
                                            Re-staking: No
                                            Winding down: Yes
                                            Snapshots: Yes
                                            Activity:  Missing 4 commitments (last time for period #2677)
                                            Worker:    0x28a375dA5AE8f3945C2093837ebBCaAb2a5917fD
                                            Unclaimed fees: 0 ETH
                                            Min fee rate: 350 gwei

Network Mainnet ══════════════════════════════════════
Staker 0xd1089adDb272221e2df019CA91395c488E83F656 ════
Worker 0x28a375dA5AE8f3945C2093837ebBCaAb2a5917fD ════
--------------  ----------------------
Status          Missing 4 commitmentss
Restaking       No
Winding Down    Yes
Snapshots       Yes
Unclaimed Fees  0 ETH
Min fee rate    350 gwei
--------------  ----------------------
╒════════╤══════════════════════════════╤═════════════╤═════════════╤═══════════════╤═════════╤══════════╕
│   Slot │ Value                        │   Remaining │ Enactment   │ Termination   │ Boost   │ Status   │
╞════════╪══════════════════════════════╪═════════════╪═════════════╪═══════════════╪═════════╪══════════╡
│      0 │ 707672.581423774377175896 NU │          -3 │ Oct 14 2020 │ Apr 28 2021   │ 0.94x   │ UNLOCKED │
╘════════╧══════════════════════════════╧═════════════╧═════════════╧═══════════════╧═════════╧══════════╛
```

**Comment by mswilkison** [comment]
probably makes sense to remove imo

**Comment by derekpierre** [comment]
> probably makes sense to remove imo

done!

**Review by KPrasch — APPROVED** [review]
Thanks @derekpierre

**Pull request merged**
