### PR TITLE
add DELIGHT profile

### PR DESCRIPTION
**Pull request by jhlee-young**

### CODE REVIEW

**Comment by derekpierre** [comment]
@jhlee-young - do you intend to be a node-as-a-service provider for PRE on the Threshold Network, <https://interim-pre-application-docs.readthedocs.io/en/latest/>?

**Comment by jhlee-young** [comment]
> @jhlee-young - do you intend to be a node-as-a-service provider for PRE on the Threshold Network, https://interim-pre-application-docs.readthedocs.io/en/latest/?

sure I do, can't wait 6.0.0!

**Comment by derekpierre** [comment]
It seems that you did not provide any node-as-a-service functionality on mainnet when PRE was running on NuCypher Network, and NuCypher wasn't even mentioned as a service on your website. This is why your original information was removed via <https://github.com/nucypher/validator-profiles/pull/40>. Is there a concrete plan? - service information on your website, providing support on the Threshold Discord (https://discord.gg/threshold) etc.

**Comment by caramis** [comment]
@derekpierre We operated workers for our team and other entities who have locked NU. And we *will* intend to be a node-as-a-service provider.
Is there anything we need to prepare in advance? Please let us know. We will prepare.

**Comment by derekpierre** [comment]
A commitment is sufficient.

I recommend your team join the Threshold Discord - https://discord.gg/threshold to respond to any questions from the community.

**Comment by derekpierre** [comment]
@jhlee-young, we are looking into listing Threshold-wide staking providers in centralized Threshold Documentation. I know you ran PRE nodes previously, is there the intention to run a node for tBTC as well (and potentially other Threshold applications) in the future once launched?

If you would like us to create a private channel for you on the [Threshold Discord server](https://discord.gg/threshold), let us know.

**Comment by derekpierre** [comment]
We'll need Discord usernames for members of your team.

**Comment by jhlee-young** [comment]
our members' usernames in Threshold Discord below:
bryan | DELIGHT#4761
Joon | DELIGHT#8129
Joowon | DELIGHT#0558
Yeon | DELIGHT#7235
Young | DELIGHT#4431

**Pull request merged**
